all:  clear compile run clean

compile:
	@echo "Compiling..."
	@g++ -std=c++11 Bulldozer.cpp Human.cpp Optimusprime.cpp Robocop.cpp Robot.cpp Roomba.cpp main.cpp -o pa5

run:
	@echo "Running.."
	@echo "--------------------------------------------------------------"
	@./pa5
clean:
	@rm pa5 
clear:
	@echo "Clear the terminal."
	@clear